### ISSUE TITLE
v0.2.2 not pushed to crates.io

### ISSUE THREAD

**Issue by yanns** [conradludgate/circleci-junit-fix#3]
Hi,

first thanks for your crate.

There's a [v0.2.2](https://github.com/conradludgate/circleci-junit-fix/releases/tag/v0.2.2) in github, but it does not seem to exist on [crates.io where "only" the v0.2.1 exists](https://crates.io/crates/circleci-junit-fix)

**Comment by yanns** [comment]
@conradludgate would you have time looking for this?

**Comment by conradludgate** [comment]
I cannot publish it due to yanked packages. I would have to fix the dependencies in order to publish it.

**Comment by conradludgate** [comment]
Released v0.2.3

**Comment by yanns** [comment]
thank you so much!

**Comment by yanns** [comment]
I can confirm it's working now.
